<?php

/**
 * @file
 * Lynx module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function lynx_form_system_site_information_settings_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $domain = \Drupal::config('lynx.domain.settings')->get('lynx_domain');
  $form['lynx'] = [
    '#type' => 'details',
    '#title' => t('Lynx'),
    '#open' => TRUE,
  ];
  $form['lynx']['lynx_domain'] = [
    '#title' => t('Lynx Domain'),
    '#type' => 'textfield',
    '#default_value' => $domain,
    '#description' => t('Enter the Lynx domain for which the redirection would happen.'),
  ];
  $form['#submit'][] = 'lynx_domain_form_submit';
}

/**
 * Save Lynx domain in config.
 */
function lynx_domain_form_submit(&$form, FormStateInterface $formState) {
  $domain = $formState->getValue('lynx_domain');
  if ($domain) {
    $lynx_settings = \Drupal::configFactory()->getEditable('lynx.domain.settings');
    $lynx_settings->set('lynx_domain', $domain)
      ->save();
  }
}
